# PyTorch Fundamentals - Day 9 Notebook
# Foundations of Neural Networks and Deep Learning

## 1. Introduction to PyTorch
PyTorch is an open-source machine learning framework developed by Facebook AI in 2016. It combines GPU-accelerated backend libraries with a Python frontend, making it ideal for rapid prototyping and deep learning model development.

In [2]:
# Import PyTorch
import torch
import numpy as np
print(f"PyTorch version: {torch.__version__}")

PyTorch version: 2.8.0+cpu


## 2. Tensors - The Building Blocks
Tensors are multidimensional arrays, similar to NumPy's ndarrays, but can run on GPUs. They encode inputs, outputs, and model parameters.

In [3]:
# Creating tensors in different ways

# Empty tensor (uninitialized)
x = torch.empty(3, 4)
print("Empty tensor (3x4):")
print(x)

# Tensor with zeros
zeros = torch.zeros(2, 3)
print("\nZeros tensor:")
print(zeros)

# Tensor with ones
ones = torch.ones(2, 3)
print("\nOnes tensor:")
print(ones)

# Random tensor (values between 0 and 1)
random_tensor = torch.rand(2, 3)
print("\nRandom tensor:")
print(random_tensor)

Empty tensor (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Zeros tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random tensor:
tensor([[0.2457, 0.6059, 0.3562],
        [0.5347, 0.3922, 0.0860]])


In [4]:
# Setting random seed for reproducibility
torch.manual_seed(42)
reproducible_random = torch.rand(2, 3)
print("Reproducible random tensor:")
print(reproducible_random)

Reproducible random tensor:
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:

data = [[1, 2, 3], [4, 5, 6]]
tensor_from_list = torch.tensor(data)
print("Tensor from list:")
print(tensor_from_list)


numpy_array = np.array([[1, 2], [3, 4]])
t1 = torch.tensor(  numpy_array)
t2=torch.Tensor(numpy_array)
t3=torch.from_numpy(numpy_array)
t4=torch.as_tensor(numpy_array)
print("\nTensor from NumPy:")
print(t1)
print(t2)
print(t3)
print(t4)

Tensor from list:
tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor from NumPy:
tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [10]:
numpy_array[0]=0
print(t1)
print(t2)
print(t3)
print(t4)

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[0, 0],
        [3, 4]])
tensor([[0, 0],
        [3, 4]])


## 3. Tensor Attributes and Properties

In [5]:
# Tensor attributes
tensor = torch.rand(3, 4)

print(f"Shape: {tensor.shape}")
print(f"Data type: {tensor.dtype}")
print(f"Device: {tensor.device}")
print(f"Number of elements: {tensor.numel()}")

Shape: torch.Size([3, 4])
Data type: torch.float32
Device: cpu
Number of elements: 12


In [6]:
# Creating tensors with specific data types
float_tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
bool_tensor = torch.tensor([True, False, True], dtype=torch.bool)

print(f"Float tensor: {float_tensor}, dtype: {float_tensor.dtype}")
print(f"Int tensor: {int_tensor}, dtype: {int_tensor.dtype}")
print(f"Bool tensor: {bool_tensor}, dtype: {bool_tensor.dtype}")

Float tensor: tensor([1., 2., 3.]), dtype: torch.float32
Int tensor: tensor([1, 2, 3]), dtype: torch.int64
Bool tensor: tensor([ True, False,  True]), dtype: torch.bool


In [7]:
# Using torch.arange()
range_tensor = torch.arange(10)
print("Range 0-9:", range_tensor)

range_tensor_step = torch.arange(0, 10, 2)
print("Range 0-10 with step 2:", range_tensor_step)

Range 0-9: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Range 0-10 with step 2: tensor([0, 2, 4, 6, 8])


## 4. Tensor Operations

In [8]:
# Basic operations
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Element-wise addition
print("Addition:")
print(x + y)
print(torch.add(x, y))

# Element-wise multiplication
print("\nMultiplication:")
print(x * y)
print(torch.mul(x, y))

# Scalar operations
print("\nScalar addition:")
print(x + 2)

print("\nScalar multiplication:")
print(x * 2)

Addition:
tensor([[ 6,  8],
        [10, 12]])
tensor([[ 6,  8],
        [10, 12]])

Multiplication:
tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])

Scalar addition:
tensor([[3, 4],
        [5, 6]])

Scalar multiplication:
tensor([[2, 4],
        [6, 8]])


In [9]:
# Matrix multiplication
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# Using matmul
result1 = torch.matmul(a, b)
print("Matrix multiplication (matmul):")
print(result1)

# Using @ operator
result2 = a @ b
print("\nMatrix multiplication (@):")
print(result2)

# Transpose
print("\nTranspose of a:")
print(a.T)

Matrix multiplication (matmul):
tensor([[19, 22],
        [43, 50]])

Matrix multiplication (@):
tensor([[19, 22],
        [43, 50]])

Transpose of a:
tensor([[1, 3],
        [2, 4]])


In [13]:
# Squeeze and unsqueeze
x = torch.rand(1, 3, 4)
print(f"Original shape: {x.shape}")

# Remove dimensions of size 1
squeezed = torch.squeeze(x)
print(f"After squeeze: {squeezed.shape}")

# Add dimension of size 1
unsqueezed = torch.unsqueeze(squeezed, dim=0)
print(f"After unsqueeze at dim=0: {unsqueezed.shape}")

Original shape: torch.Size([1, 3, 4])
After squeeze: torch.Size([3, 4])
After unsqueeze at dim=0: torch.Size([1, 3, 4])


## 5. Autograd - Automatic Differentiation
PyTorch's autograd feature automatically computes gradients for backpropagation.

In [ ]:
# Create tensors with gradient tracking
x = torch.tensor([2.0, 3.0], requires_grad=True)
print(f"x: {x}")


y = x ** 2
z = y.sum()

print(f"y = x^2: {y}")
print(f"z = sum(y): {z}")

# Compute gradients
z.backward()
print(f"Gradient dz/dx: {x.grad}")

x: tensor([2., 3.], requires_grad=True)
y = x^2: tensor([4., 9.], grad_fn=<PowBackward0>)
z = sum(y): 13.0
Gradient dz/dx: tensor([4., 6.])


In [20]:
# Example: Computing gradients for a simple function
x = torch.tensor(3.0, requires_grad=True)

# f(x) = 2x^2 + 3x + 1
y = 2 * x**2 + 3 * x + 1

print(f"f(3) = {y.item()}")

# Compute gradient: f'(x) = 4x + 3
y.backward()
print(f"f'(3) = {x.grad}")
print(f"Expected: {4*3 + 3}")

f(3) = 28.0
f'(3) = 15.0
Expected: 15


## 6. Working with Datasets

In [14]:
from torch.utils.data import Dataset, DataLoader

# Create a simple custom dataset
class SimpleDataset(Dataset):
    def __init__(self, size=100):
        self.x = torch.randn(size, 10)
        self.y = torch.randint(0, 2, (size,))
    
    def __len__(self):
        return len(self.x)
    
    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]


dataset = SimpleDataset(size=100)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

print(f"Dataset size: {len(dataset)}")
print(f"Number of batches: {len(dataloader)}")


for batch_x, batch_y in dataloader:
    print(f"Batch X shape: {batch_x.shape}")
    print(f"Batch Y shape: {batch_y.shape}")
    break

Dataset size: 100
Number of batches: 7
Batch X shape: torch.Size([16, 10])
Batch Y shape: torch.Size([16])


## 7. Building Neural Networks
Neural networks are built using `torch.nn.Module` as the base class.

In [15]:
# Complete MNIST FCNN Training in a Single Cell

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

# Set device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Define the FCNN model
class FCNN(nn.Module):
    def __init__(self):
        super(FCNN, self).__init__()
        self.fc1 = nn.Linear(28*28, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, 128)
        self.fc4 = nn.Linear(128, 10)
        
    def forward(self, x):
        x = x.view(-1, 28*28)  # Flatten
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.relu(self.fc3(x))
        x = self.fc4(x)
        return x

# Load MNIST dataset
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])
train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=1000, shuffle=False)

# Initialize model, loss, and optimizer
model = FCNN().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
num_epochs = 5
for epoch in range(num_epochs):
    model.train()
    train_loss, correct, total = 0, 0, 0
    
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        
        train_loss += loss.item()
        _, predicted = torch.max(output.data, 1)
        total += target.size(0)
        correct += (predicted == target).sum().item()
    
    # Evaluation
    model.eval()
    test_loss, test_correct, test_total = 0, 0, 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss += criterion(output, target).item()
            _, predicted = torch.max(output.data, 1)
            test_total += target.size(0)
            test_correct += (predicted == target).sum().item()
    
    print(f'Epoch [{epoch+1}/{num_epochs}]')
    print(f'  Train Loss: {train_loss/len(train_loader):.4f}, Train Acc: {100*correct/total:.2f}%')
    print(f'  Test Loss: {test_loss/len(test_loader):.4f}, Test Acc: {100*test_correct/test_total:.2f}%')

print('\nTraining complete!')

Using device: cpu
Epoch [1/5]
  Train Loss: 0.2216, Train Acc: 93.22%
  Test Loss: 0.1079, Test Acc: 96.71%
Epoch [2/5]
  Train Loss: 0.0961, Train Acc: 97.08%
  Test Loss: 0.0745, Test Acc: 97.63%
Epoch [3/5]
  Train Loss: 0.0672, Train Acc: 97.88%
  Test Loss: 0.0776, Test Acc: 97.57%
Epoch [4/5]
  Train Loss: 0.0505, Train Acc: 98.41%
  Test Loss: 0.0873, Test Acc: 97.41%
Epoch [5/5]
  Train Loss: 0.0426, Train Acc: 98.66%
  Test Loss: 0.0705, Test Acc: 97.77%

Training complete!
