In [23]:
import numpy as np
import matplotlib.pyplot as plt

In [43]:
# Toy dataset: Area (sqft) vs Price (lakhs)

X = np.array([500, 800, 1000, 1200, 1500, 1800, 2000, 2500])
y=np.array([ 70, 100, 120, 140, 170, 200, 220, 270])

print("Areas:", X)
print("Prices:", y)


Areas: [ 500  800 1000 1200 1500 1800 2000 2500]
Prices: [ 70 100 120 140 170 200 220 270]


In [44]:
#normalise the input X using minmax

a=(1600-np.min(X))/(np.max(X)-np.min(X))
a

np.float64(0.55)

In [ ]:
X=(X-np.min(X))/(np.max(X)-np.min(X))
X

In [46]:
# now lets train the network to identify the weights and bias
# initialise ranom weights and bias
np.random.seed(11)
w=np.random.rand()
b=0

In [47]:
def prediction(X, w, b):
    return np.dot(w, X)+b

In [48]:
epoch=1000
n=len(X)
alpha=1e-4
for __ in range(epoch):
    y_pred=prediction(X, w, b)
    dw=(-2/n)*(np.sum(X*(y-y_pred)))
    db=(-2/n)*(np.sum((y-y_pred)))
    w=w-alpha*dw
    b=b-alpha*db


print(w, b)

nan nan


c:\PythonEnv\Lib\site-packages\numpy\_core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\Gagan\AppData\Local\Temp\ipykernel_27584\1774199068.py:8: RuntimeWarning: invalid value encountered in scalar subtract
  w=w-alpha*dw


In [49]:
print(prediction(X, w, b))
y

# our prediction matches the output!!

[nan nan nan nan nan nan nan nan]


array([ 70, 100, 120, 140, 170, 200, 220, 270])

In [32]:
prediction(a, w, b)

np.float64(nan)

In [53]:
import numpy as np

# Toy dataset
X = np.array([500, 800, 1000, 1200, 1500, 1800, 2000, 2500])
y = np.array([70, 100, 120, 140, 170, 200, 220, 270])

def prediction(X, w, b):
    return w * X + b

# Initialize
np.random.seed(11)
w = np.random.rand()
b = 0.0

print(f"Initial w: {w}, b: {b}")

# Training with MUCH smaller learning rate
epoch = 5000  # More epochs since we're going slower
n = len(X)
alpha = 1e-6  # Try this tiny learning rate!

for i in range(epoch):
    y_pred = prediction(X, w, b)
    dw = (-2/n) * (np.sum(X * (y - y_pred)))
    db = (-2/n) * (np.sum((y - y_pred)))
    w = w - alpha * dw
    b = b - alpha * db
    
    # Print every 500 iterations
    if i % 500 == 0:
        loss = np.mean((y - y_pred)**2)
        print(f"Epoch {i}: w={w:.6f}, b={b:.6f}, loss={loss:.2f}")

print(f"\nFinal w: {w}, b: {b}")
print(f"Predictions: {prediction(X, w, b)}")
print(f"Actual:      {y}")

Initial w: 0.1802696888767692, b: 0.0
Epoch 0: w=-0.145916, b=-0.000187, loss=11223.80
Epoch 500: w=-274128723211639035352789989117741175904013097804688186237460966025396475356382701672732967025254975983931041316955661677045283577938436411383541022228057343820344863668432422115376321295284919601210577032308659427538520570014105563697195124569641438438323193660261084967270334253051674624.000000, b=-162436013850612317093506689591340616659260874234647921808221150016745346093981026858142744148642149887782484617228339888124200037106685335149787302076675614491431557615213042840525641650733487787621667858327077101729606911877550689102376276476831958580896180498617163796744301466091520.000000, loss=inf
Epoch 1000: w=nan, b=nan, loss=nan
Epoch 1500: w=nan, b=nan, loss=nan
Epoch 2000: w=nan, b=nan, loss=nan
Epoch 2500: w=nan, b=nan, loss=nan
Epoch 3000: w=nan, b=nan, loss=nan
Epoch 3500: w=nan, b=nan, loss=nan
Epoch 4000: w=nan, b=nan, loss=nan
Epoch 4500: w=nan, b=nan, loss=nan

Final w: nan, b

C:\Users\Gagan\AppData\Local\Temp\ipykernel_27584\1716349405.py:31: RuntimeWarning: overflow encountered in square
  loss = np.mean((y - y_pred)**2)
C:\Users\Gagan\AppData\Local\Temp\ipykernel_27584\1716349405.py:26: RuntimeWarning: invalid value encountered in scalar subtract
  w = w - alpha * dw


In [ ]:
# initialise ranom weights and bias
np.random.seed(11)
w=np.random.rand()
b=0
w

0.1802696888767692

In [56]:
#our intial w is 0.18 
y_pred =prediction(X, w, b) 
y_pred 

array([ 90.13484444, 144.2157511 , 180.26968888, 216.32362665,
       270.40453332, 324.48543998, 360.53937775, 450.67422219])

In [57]:
y-y_pred

array([ -20.13484444,  -44.2157511 ,  -60.26968888,  -76.32362665,
       -100.40453332, -124.48543998, -140.53937775, -180.67422219])

In [58]:
dw = (-2/n) * (np.sum(X * (y - y_pred)))
dw

np.float64(326185.74171999714)

In [59]:
alpha=0.01
w=w-alpha*dw
w

np.float64(-3261.677147511095)

In [60]:
#now our new w is -3261.677
# lets do the step again

y_pred=prediction(X,w, b)
y_pred

array([-1630838.57375555, -2609341.71800888, -3261677.14751109,
       -3914012.57701331, -4892515.72126664, -5871018.86551997,
       -6523354.29502219, -8154192.86877774])

In [61]:
y-y_pred

array([1630908.57375555, 2609441.71800888, 3261797.14751109,
       3914152.57701331, 4892685.72126664, 5871218.86551997,
       6523574.29502219, 8154462.86877774])

In [62]:
dw = (-2/n) * (np.sum(X * (y - y_pred)))
dw

np.float64(-15550579050.759144)

In [ ]:
alpha=0.01
w=w-alpha*dw
w
# w is too large in just 2 epochs, for 100 epochs it will reach infinity or nan

np.float64(155502528.83044395)