In [39]:
import numpy as np
import matplotlib.pyplot as plt

In [40]:
# Toy dataset: Area (sqft) vs Price (lakhs)

X = np.array([500, 800, 1000, 1200, 1500, 1800, 2000, 2500])
y=np.array([ 70, 100, 120, 140, 170, 200, 220, 270])

print("Areas:", X)
print("Prices:", y)


Areas: [ 500  800 1000 1200 1500 1800 2000 2500]
Prices: [ 70 100 120 140 170 200 220 270]


In [49]:
#normalise the input X using minmax

X=(X-np.min(X))/(np.max(X)-np.min(X))
X

array([0.  , 0.15, 0.25, 0.35, 0.5 , 0.65, 0.75, 1.  ])

In [50]:
# now lets train the network to identify the weights and bias
# initialise ranom weights and bias
np.random.seed(11)
w=np.random.rand()
b=0

In [51]:
def prediction(X, w, b):
    return np.dot(w, X)+b

In [65]:
epoch=1000
n=len(X)
alpha=1e-5
for __ in range(epoch):
    y_pred=prediction(X, w, b)
    dw=(-2/n)*(np.sum(X*(y-y_pred)))
    db=(-2/n)*(np.sum((y-y_pred)))
    w=w-alpha*dw
    b=b-alpha*db
print(w, b)

199.99999999999108 70.00000000000442


In [ ]:
print(prediction(X, w, b))
y

# our prediction matches the output!!

[ 70. 100. 120. 140. 170. 200. 220. 270.]


array([ 70, 100, 120, 140, 170, 200, 220, 270])